source 'http://rubygems.org'

gem 'rspec'
gem 'selenium-webdriver'
gem 'capybara', '~> 2.12', '<3.0'
gem 'site_prism', '~> 2.13'
gem 'faker'
gem 'rspec_junit_formatter'
gem 'allure-rspec'
gem 'httparty'
gem 'geckodriver-helper'
gem 'chromedriver-helper'
gem 'capybara-bootstrap-datepicker'
gem 'pry_debug'
#gem 'json'
#gem 'mysql', '~> 2.9', '>= 2.9.1'
#gem 'mongo'

