source 'http://rubygems.org'

gem 'rspec'
gem 'selenium-webdriver', '~> 2.53', '>= 2.53.4'
gem 'capybara'
gem 'site_prism'
gem 'faker'
gem 'mongo'
gem 'rspec_junit_formatter'
gem 'allure-rspec'
gem 'httparty'